http_requester.bat data_find_product_code.json
SLEEP 2
http_requester.bat data_view_details.json
SLEEP 2
http_requester.bat data_put_to_cart.json
SLEEP 2
http_requester.bat data_select_color.json
SLEEP 2
http_requester.bat data_select_size.json
SLEEP 2
http_requester.bat data_select_quantity.json
SLEEP 2
http_requester.bat data_purchase_now.json